### ISSUE TITLE
great site, found this accidentally 

### ISSUE THREAD

**Issue by artemartemov** [tjFogarty/personal-site#2]
hey there, great site. came across the blog when I was looking for a new FE workflow with mix. funny enough that it looks like someone in Chine has literally copy/pasted your articles as their own with minor adjustments - wasn't sure where to post so here we are!

https://hk.saowen.com/a/459a33a40a00106f936feeafae40a364f04c8f74faf0112ba6b785357295423d

**Comment by tjFogarty** [comment]
Hey, thanks for the kind comment! Huh, that's strange. It all links back to my site, and has my site as a source/author? Thanks for letting me know :)
